const el=id=>document.getElementById(id);
const put=(id,value)=>{el(id).textContent=value};
const ms=v=>v==null?'—':`${Math.round(v)} ms`;
const labels={playing:'진행 중',passed:'통과',failed:'탈락',waiting:'대기',running:'진행 중',stopped:'정지',finished:'종료'};
function rows(id,items,empty){const box=el(id);box.replaceChildren();box.className=items.length?'':'empty';if(!items.length){box.textContent=empty;return}for(const [left,right,status] of items){const row=document.createElement('div');row.className='row';const a=document.createElement('span'),b=document.createElement('span');a.textContent=left;b.textContent=right;b.className=status||'';row.append(a,b);box.append(row)}}
async function get(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw Error(`${path}: ${response.status}`);return response.json()}
async function refresh(){let ok=true;try{const v=await get('/api/vision');const stale=v.result_age_ms>2000;put('source',v.source==='video'?'영상 테스트 · 1×':'웹캠 · 실시간');put('vision-state',stale?'관측 지연':({preparing:'엔진 준비 중',running:'검출 중',ended:'영상 종료',error:'입력 오류'}[v.state]||v.state));put('people',v.people??'—');put('processing',ms(v.processing_ms));put('interval',ms(v.interval_ms));put('age',ms(v.result_age_ms));el('overlay').hidden=v.state==='running'&&!stale;el('overlay').textContent=v.error|| (stale?'관측이 지연되었습니다. 마지막 검출 화면입니다.':v.state==='ended'?'영상 재생이 종료되었습니다.':'추론 엔진을 준비하고 있습니다');put('tracks',`임시 추적 ID: ${(v.track_ids||[]).join(', ')||'—'}`);rows('candidates',(v.candidates||[]).map(c=>[`추적 ID ${c.track_id}`,`통과 후보 · ${c.crossed_at.toFixed(2)}초`]),'결승선 통과 후보 없음');document.querySelector('.panel .note').textContent=`미리보기 최대 ${v.preview_hz||5} FPS · 추론 속도와 별개입니다. 영상 테스트는 원본 시간으로 재생합니다.`;}catch(e){ok=false;put('vision-state','서버 연결 끊김');el('overlay').hidden=false;el('overlay').textContent='서버 연결을 확인해 주세요';if(el('stream').dataset.retry!=='1'){el('stream').dataset.retry='1'}}
try{const g=await get('/api/game');if(g.game){put('game-state',(g.game.is_test?'시험 데이터 · ':'')+(labels[g.game.phase]||g.game.phase));const t=g.game.remaining_seconds;put('remaining',t==null?'— : —':`${Math.floor(t/60)} : ${String(t%60).padStart(2,'0')}`);put('game-meta',`게임 ${g.game.id} · 상태 갱신 ${g.game.updated_at}`);put('total',g.participants.length);put('passed',g.participants.filter(p=>p.status==='passed').length);put('failed',g.participants.filter(p=>p.status==='failed').length)}else{put('game-state',g.backend==='mariadb'?'DB 연결됨 · 게임 대기':'연결 대기');put('remaining','— : —');put('game-meta','Pi 게임 상태 저장 기능을 연결하면 표시됩니다.');for(const id of ['total','passed','failed'])put(id,'—')}rows('participants',g.participants.map(p=>[p.name||p.id,labels[p.status]||p.status,p.status]),'아직 저장된 참가자 정보가 없습니다.');rows('devices',(g.devices||[]).map(d=>[d.id,d.connection_state+' · '+(d.last_seen_at||'수신 기록 없음')]),'아직 보드 상태 수집이 연결되지 않았습니다.');rows('events',g.events.map(e=>[`${e.kind}${e.participant_id?' · '+e.participant_id:''}`,e.occurred_at]),'아직 저장된 이벤트가 없습니다.')}catch(e){ok=false;put('game-state','게임 상태 조회 실패');put('game-meta','마지막 표시값일 수 있습니다. 서버 상태를 확인해 주세요.')}
put('connection',ok?'서버 연결됨':'연결 확인 필요');if(ok&&el('stream').dataset.retry==='1'){el('stream').src='/stream.mjpg?retry='+Date.now();el('stream').dataset.retry='0'}setTimeout(refresh,1000)}
el('stream').addEventListener('error',()=>{el('stream').dataset.retry='1'});refresh();
