USE mugunghwa;
ALTER TABLE games ADD COLUMN IF NOT EXISTS state_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS duration_seconds INT UNSIGNED,
 ADD COLUMN IF NOT EXISTS ended_at VARCHAR(32),
 ADD COLUMN IF NOT EXISTS end_reason VARCHAR(32);
ALTER TABLE participants ADD COLUMN IF NOT EXISTS track_id BIGINT,
 ADD COLUMN IF NOT EXISTS source_epoch BIGINT;
